### ISSUE TITLE
Check if the Attachment widget is using the correct settings

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#254]
the path is relative and warn the users if it is not.

**Comment by wonder-sk** [comment]
Also check "Default path":
- sometimes people have their local path (e.g. C:/....) entered there - that will not work in Input
- sometimes people try to use expression-based path (e.g. `@project_home + '/photos'`) but they enter it as the default path rather than clicking the button to set data-defined path
