### ISSUE TITLE
Convert survey layers to GPKG

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#55]
There are several issues with non-gpkg layers as survey layer. Best to have them converted to gpkg as a part of plugin.

**Comment by dracic** [comment]
I have a question about GPKG layers and Mergin support. Since GPKG layers have mandatory primary key field (feature id), and QGIS creates that field as auto increment integer, doesn't that make GPKG format less suitable for multiuser sync? So every user starts with 1,2,3..., and at the moment if you try to sync GPKG survey layer from multiple devices you will get sync_errors beacuse of primary key violation.

**Comment by saberraz** [comment]
Hi @dracic 

With the recent version of the mergin plugin and the APK from here https://github.com/lutraconsulting/input/pull/489 (https://www.dropbox.com/s/p6zoq70i9nesafw/input-489-330128471ae7a19aaf26669b7e9b09b3793b7005-arm64_v8a-signed.apk) you should be able to do edits from multiple sources/users to the same geopackage. Geodiff handles all changes and consolidates the diffs from multiple clients.

Please note that the Input APK is still beta. But if you are doing some trails, would be good to use the APK and let us know your feedback/suggestions.

**Comment by dracic** [comment]
Great! I will try it ASAP!

**Comment by wonder-sk** [comment]
Implemented in #194
